Añadido docker y opción de exportar listas
mx-psi/tidbits pull request #2
Opened 2020-04-25 17:55 UTC by sdecandelario

Se ha añadido una imagen docker para facilitar el desarrollo y la ejecución del script, he adaptado el README para que se sepa como ejecutar, lo suyo sería subir la imagen resultante a [Hub Docker](https://hub.docker.com/) y así no tener que crearla cada vez.

Por otra parte he añadido la opción de exportar las películas que estén en una lista. La lista ha de ser pública o por ahora no está soportado ya que no se ha implementado el login del usuario.

Cualquier comentario o mejora que se pueda hacer encantado :)

2020-04-27 18:40 UTC, mx-psi requested changes
Lo veo guay, aunque me gustaría unificar de alguna forma `get_list_data` y `get_profile_data` y extraer la parte común. Te he dejado un par de comentarios de cosas que cambiar o que no entiendo.

2020-04-27 18:40 UTC, mx-psi commented on faLetterboxd/README.md
> +- `--list LIST` The id of the public list you wanna export, if is available export the list and not your ratings
¿Te importa documentar cómo sacar la id de la lista? Alguna gente que lo ha usado no sabe mucho de informática y a lo mejor no es trivial para ellxs

2020-04-27 18:40 UTC, mx-psi commented on faLetterboxd/README.md
> +`docker run --name fa-letterboxd fa-letterboxd python3 faScrap.py --lang en --csv fa-to-lbx.csv 702720 && docker cp fa-letterboxd:/fa-to-lbx.csv . && docker rm fa-letterboxd`
No entiendo de dónde sale el `702720`

2020-04-27 18:52 UTC, sdecandelario commented on faLetterboxd/README.md
> +- `--list LIST` The id of the public list you wanna export, if is available export the list and not your ratings
Okey! Miro de ponerlo, pro básicamente es ir a tu perfil público y ahí ir a la lista que quieras.

2020-04-27 18:52 UTC, sdecandelario commented on faLetterboxd/README.md
> +`docker run --name fa-letterboxd fa-letterboxd python3 faScrap.py --lang en --csv fa-to-lbx.csv 702720 && docker cp fa-letterboxd:/fa-to-lbx.csv . && docker rm fa-letterboxd`
Es ese me a colado, ha de ser el id del usuario, lo cambio

2020-04-27 19:06 UTC, sdecandelario commented
Totalmente de acuerdo en unificarlo, si tienes alguna idea lo podemos mirar, yo por ahora solamente hice que funcionase, pero está claro que puede ser más óptimo

2020-04-27 19:09 UTC, sdecandelario commented on faLetterboxd/README.md
> +- `--list LIST` The id of the public list you wanna export, if is available export the list and not your ratings
He añadido esta sección debajo de como obtener el id, así queda más claro todo

2020-04-29 17:38 UTC, mx-psi commented
Pensándolo un poco, creo que lo mejor para abstraer es hacer una función 

```python
def pages_from(template):
   # . . .
```
que devuelva un iterable (idealmente un generador) que te dé cada página parseada, para luego implementar:

```python
def get_list_data(user_id, list_id, lang):
  data = []
  FA = "https://www.filmaffinity.com/" + lang + \
       "/userlist.php?user_id={user_id}&list_id={list_id}&page={{n}}"
       .format(...)

  for page in pages_from(FA):
      # Rellena data como se hacía antes
      ...

  return data

```

Creo que ese nivel de abstracción está bien y es reutilizable en otros contextos (por ejemplo, sacar las críticas de un usuario). Si no te apetece implementarlo a ti lo hago yo este finde.

2020-04-29 18:34 UTC, sdecandelario commented
Si no te es molestia preferirá que está parte de los itetadores lo hicieras tu y cuando lo tengas me avises y así miro como lo has hecho y aprendo 😊

2020-04-29 18:36 UTC, mx-psi commented
Okay, np, el finde me pongo a ello

2020-05-01 14:29 UTC, merged

2020-05-01 14:31 UTC, mx-psi reviewed
Mergeado! Si quieres ver la función `pages_from` [aquí](https://github.com/mx-psi/tidbits/blob/3cee1338a01f7cac6497d9c86fe235661f57ed0f/faLetterboxd/faScrap.py#L71-L88) la tienes :)

2020-05-01 14:55 UTC, sdecandelario commented
Pues muchas @mx-psi gracias por hacer la adaptación de los generators, ahroa queda mucho más limpio y es extensible a más funcionalidades :)

2020-05-01 15:26 UTC, mx-psi commented
Sí! Lo acabo de cambiar y he reescrito `get_profile_data` y `get_list_data` usando generadores también (así no hay que generar una lista de películas sino que simplemente se van escribiendo en el CSV conforme se descargan los datos)

2020-05-01 15:58 UTC, sdecandelario commented
Wow, la verdad es que ha dado de si la PR, jajaja, ahora si que se ve mucho mejor :)